# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "es-ES"
title                    : "Biel Pons / Enciclopédia de frutas demoníacas"
title_separator          : "-"
name                     : &name "Biel Pons"
description              : &description "Enciclopédia de frutas demoníacas"
markdown: kramdown
url: https://biel-pons.github.io
highlighter: rouge
theme: jekyll-theme-minimal
